# Use container-based infrastructure
sudo: false

jdk: oraclejdk7

language: scala

scala:
  - 2.10.5

script:
  - rm -rf $HOME/.sbt
  - rm -rf $HOME/.ivy2
  - sbt ++$TRAVIS_SCALA_VERSION -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M scripted
